import Product from "@/components/Product.js";
import Head from "next/head";
import Link from "next/link";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query.js";
export default function Home() {
	 //Fetch products from strapi
	 const [results] = useQuery({ query: PRODUCT_QUERY });
	 const { data, fetching, error } = results;
   
	 //Checks for the data coming in
	 if (fetching) return <p>Loading...</p>;
	 if (error) return <p>Oh no... {error.message}</p>;
	 const products = data.products.data;
	 console.log(products)
	return (
		<>
			<Head>
				<title>Best Ecommerce shop in 2023</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>Hello next</h1>
				{products.map((product)=>(
					<Product key={product.attributes.slug} product={product}/>
				))}
				<Link href={"/about"}>About</Link>
			</main>
		</>
	);
}
